[package]
name = "aoc-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
criterion = "0.5"
colored = "2.0"
regex = "1"
num-traits = "0.2"
rustc-hash = "2"
